options: 
  int-option: 
    default: 9001
    description: "A short description of the configuration option"
    type: int
  string-option: 
    default: "Default Value"
    description: "A short description of the configuration option"
    type: string
  boolean-option: 
    default: false
    description: "A short description of the configuration option"
    type: boolean
  install_sources:
    # description and type comes from the apt layer.
    default: |
      - deb http://apt.openattic.org/ trusty main
      - deb https://download.ceph.com/debian-jewel trusty main
  install_keys:
    # description and type comes from the apt layer.
    default: |
      - |
          -----BEGIN PGP PUBLIC KEY BLOCK-----
          Version: GnuPG v1

          mQENBE9UiJQBCADXaeyPt9tZLeC3cRQX33BP22hG8LRp4MBdoyC95/VP6sFp7i6r
          y1djlAUxED0w8DPINxuDlez5PBUP1Dwq3NzJ8f1aeUyvvcIFnAwnafcfcjFO0D5X
          1F6bSl0FDj32c5Ro47bkI2UgEX7hb+8uX6Z3iGqPa1v24MsLxB3nxihgXJIXfDM4
          7TzijoxvgQkqF1fKjiRdlETGX0/SqVhxirPTrpnAAY84G5OOPvmgaxPZIZ6lQrzg
          0x1sTBl9j1fK0bpq1GK58cMJB4CndbqBe4bLi0okSBWV029+QGDzTk1wQw2hIiY9
          wD7vzxmkoWaQr7p7QlCmzU3DGzjPq39i3+yhABEBAAG0MUJ1c2luZXNzIENyaXRp
          Y2FsIENvbXB1dGluZyA8aXMtYmNjQGl0LW5vdnVtLmNvbT6JATgEEwECACIFAk9U
          iJQCGwMGCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJEB1c1E2n0+r6MtEIAK2W
          1S2bYNGKvsXxhNflKDktlPQpnkmthGX0+3V/9PnE1hTKH/Mzmr01QlfmM8qTpma3
          Z/Es1DVfGZmh6ZNbFgoVeMVEaZvrHhSlfKT9QMcA/cMnRsk9BaWqQ01G18N4rydh
          IAHYnPwcT+16WTYb5qBS8N+1dAYXCIknJPs45ur2QMqfc5IrUX5Cs14kwym4RZAn
          8Y9pMHgoycVZSMxMR6NOUfJ5QuaUABJ2RcEdfycv0ydhSld47SfNc52ncIEF2aVK
          6PRZyuSGh2g89YuNH+sRRrfS76AsSwLESFMH0Ks1KBJUGtVAT4m0uofr46NxlYti
          UxiI0m/XZbWulBhsbm+5AQ0ET1SIlAEIALsOTZMwSYQreTB8SN7ZyI6TlGbIfzFf
          0aHaw7MJKHtoRWojp+eZIozhQP4sVFWRH27Hx3tmkEsiuhnb6TOU7JIfXXFIXjEo
          1iPAZ/yRGhVLh9O/nDrwwvXb3fwdTdS05EI+7fpbLXWBK7KPYFp42fh9I6HINMdo
          9HACk9sLPzWqsHA+S/SGCPJ8CwifyYwfe14nG5STY95APi+iYdxAZ3Qes7TPrFvG
          qUlRAgNQeLOPFXF0qnSCgfMcQVu7JibyK5YYRQ2wmhYK4wnlM9h6oPdarur8/t9K
          JemFPM85O+Pfknuu+4HOrr1acziekv03YRkuvcjBQu+LBbL9D1JrlBcAEQEAAYkB
          HwQYAQIACQUCT1SIlAIbDAAKCRAdXNRNp9Pq+pUKCACKAxI9mQDFANzbWGzKgmTD
          vvGfNjrX1ZaOynLU8DUm56+tqk8J8kRm6XAqZar8NwbUFrEyS6HCXubmn90RsrjS
          Pm7lhqwGLfp0OlX0XNV8ev5gpGp1IdkveS0b1Pd3Ksj5IIGwjz8rJh8D/rOSJh2t
          ZwMnm3hzQrCsl+CNxi7GcCaUHAXqQw1YqNKZP4OsvtEj6sBA/6HrBQR+xMMfGO1t
          GZbUKDIiJwLyvZyNxp3YRJvGrVxO/q/zOeGUdV+nI68Yox8fD9eadHdXTVtawdlf
          mK4C7aS5LpcqMGm284IjO2ZtbskTrtyx4YCh+S0jgxkeBVcDQrnPWc30TCCC2gQO
          =DgzK
          -----END PGP PUBLIC KEY BLOCK-----
      - |
          -----BEGIN PGP PUBLIC KEY BLOCK-----
          Version: GnuPG v1

          mQINBFX4hgkBEADLqn6O+UFp+ZuwccNldwvh5PzEwKUPlXKPLjQfXlQRig1flpCH
          E0HJ5wgGlCtYd3Ol9f9+qU24kDNzfbs5bud58BeE7zFaZ4s0JMOMuVm7p8JhsvkU
          C/Lo/7NFh25e4kgJpjvnwua7c2YrA44ggRb1QT19ueOZLK5wCQ1mR+0GdrcHRCLr
          7Sdw1d7aLxMT+5nvqfzsmbDullsWOD6RnMdcqhOxZZvpay8OeuK+yb8FVQ4sOIzB
          FiNi5cNOFFHg+8dZQoDrK3BpwNxYdGHsYIwU9u6DWWqXybBnB9jd2pve9PlzQUbO
          eHEa4Z+jPqxY829f4ldaql7ig8e6BaInTfs2wPnHJ+606g2UH86QUmrVAjVzlLCm
          nqoGymoAPGA4ObHu9X3kO8viMBId9FzooVqR8a9En7ZE0Dm9O7puzXR7A1f5sHoz
          JdYHnr32I+B8iOixhDUtxIY4GA8biGATNaPd8XR2Ca1hPuZRVuIiGG9HDqUEtXhV
          fY5qjTjaThIVKtYgEkWMT+Wet3DPPiWT3ftNOE907e6EWEBCHgsEuuZnAbku1GgD
          LBH4/a/yo9bNvGZKRaTUM/1TXhM5XgVKjd07B4cChgKypAVHvef3HKfCG2U/DkyA
          LjteHt/V807MtSlQyYaXUTGtDCrQPSlMK5TjmqUnDwy6Qdq8dtWN3DtBWQARAQAB
          tCpDZXBoLmNvbSAocmVsZWFzZSBrZXkpIDxzZWN1cml0eUBjZXBoLmNvbT6JAjgE
          EwECACIFAlX4hgkCGwMGCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJEOhKwsBG
          DzmUXdIQAI8YPcZMBWdv489q8CzxlfRIRZ3Gv/G/8CH+EOExcmkVZ89mVHngCdAP
          DOYCl8twWXC1lwJuLDBtkUOHXNuR5+Jcl5zFOUyldq1Hv8u03vjnGT7lLJkJoqpG
          l9QD8nBqRvBU7EM+CU7kP8+09b+088pULil+8x46PwgXkvOQwfVKSOr740Q4J4nm
          /nUOyTNtToYntmt2fAVWDTIuyPpAqA6jcqSOC7Xoz9cYxkVWnYMLBUySXmSS0uxl
          3p+wK0lMG0my/gb+alke5PAQjcE5dtXYzCn+8Lj0uSfCk8Gy0ZOK2oiUjaCGYN6D
          u72qDRFBnR3jaoFqi03bGBIMnglGuAPyBZiI7LJgzuT9xumjKTJW3kN4YJxMNYu1
          FzmIyFZpyvZ7930vB2UpCOiIaRdZiX4Z6ZN2frD3a/vBxBNqiNh/BO+Dex+PDfI4
          TqwF8zlcjt4XZ2teQ8nNMR/D8oiYTUW8hwR4laEmDy7ASxe0p5aijmUApWq5UTsF
          +s/QbwugccU0iR5orksM5u9MZH4J/mFGKzOltfGXNLYI6D5Mtwrnyi0BsF5eY0u6
          vkdivtdqrq2DXY+ftuqLOQ7b+t1RctbcMHGPptlxFuN9ufP5TiTWSpfqDwmHCLsT
          k2vFiMwcHdLpQ1IH8ORVRgPPsiBnBOJ/kIiXG2SxPUTjjEGOVgeA
          =/Tod
          -----END PGP PUBLIC KEY BLOCK-----
